## 1. Data Preparation

#### Download dataset from S3 to Local

In [4]:
!aws s3 cp s3://sagemaker-sample-files/datasets/tabular/synthetic/churn.txt ./data/

download: s3://sagemaker-sample-files/datasets/tabular/synthetic/churn.txt to data/churn.txt

#### Pick a random sample as holdout for testing

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('./data/churn.txt')
df.head(10)

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,Eve Mins,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,PA,163,806,403-2562,no,yes,300,8.162204,3,7.579174,3.933035,4,6.508639,4.065759,100,5.111624,4.928160,6,5.673203,3,True.
1,SC,15,836,158-8416,yes,no,0,10.018993,4,4.226289,2.325005,0,9.972592,7.141040,200,6.436188,3.221748,6,2.559749,8,False.
2,MO,131,777,896-6253,no,yes,300,4.708490,3,4.768160,4.537466,3,4.566715,5.363235,100,5.142451,7.139023,2,6.254157,4,False.
3,WY,75,878,817-5729,yes,yes,700,1.268734,3,2.567642,2.528748,5,2.333624,3.773586,450,3.814413,2.245779,6,1.080692,6,False.
4,WY,146,878,450-4942,yes,no,0,2.696177,3,5.908916,6.015337,3,3.670408,3.751673,250,2.796812,6.905545,4,7.134343,6,True.
5,VA,83,866,454-9110,no,no,0,3.634776,7,4.804892,6.051944,5,5.278437,2.937880,300,4.817958,4.948816,4,5.135323,5,False.
6,IN,140,737,331-5751,yes,no,0,3.229420,4,3.165082,2.440153,8,0.264543,2.352274,300,3.869176,5.393439,4,1.784765,4,False.
7,LA,54,766,871-3612,no,no,0,0.567920,6,1.950098,4.507027,0,4.473086,0.688785,400,6.132137,5.012747,5,0.417421,8,False.
8,MO,195,777,249-5723,yes,no,0,5.811116,6,4.331065,8.104126,2,4.475034,4.208352,250,5.974575,4.750153,7,3.320311,7,True.
9,AL,104,657,767-7682,yes,no,0,2.714430,7,5.138669,8.529944,6,3.321121,2.342177,300,4.328966,3.433554,5,5.677058,4,False.

In [9]:
df = df.sample(500)
df.drop('Churn?', axis=1, inplace=True)
df.head(10)

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,Eve Mins,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls
4865,NC,141,786,274-8268,yes,yes,200,12.755639,1,8.643427,6.433101,2,10.010461,4.786495,200,5.615686,6.018834,5,9.485578,2
4554,CT,82,678,788-7992,no,yes,700,2.331273,7,2.668202,4.491013,3,3.123161,5.623481,150,4.623399,5.325665,5,3.546615,7
3122,VA,21,866,330-2325,no,no,0,5.175926,3,4.216751,7.204340,2,4.571964,3.851418,300,6.143154,3.581295,6,3.304714,6
1125,RI,112,827,876-4753,yes,yes,800,9.131213,0,5.644676,0.260374,1,7.934599,8.014738,150,5.002852,5.346287,7,2.748273,7
3249,DE,121,686,442-5491,yes,yes,100,3.186041,6,0.730870,1.467722,5,2.620685,2.619791,250,3.571496,4.477612,4,1.100553,5
1503,RI,128,827,763-4923,no,no,0,1.608495,4,5.699568,5.744440,9,0.157742,2.136105,350,3.575540,3.974274,4,3.835815,4
4089,MS,75,778,823-3572,no,yes,800,2.181899,4,4.489855,2.352469,4,4.567112,4.791327,350,3.107584,4.383725,7,2.351551,6
3883,OH,144,797,969-6819,yes,no,0,6.889680,2,7.658721,5.935497,2,5.565142,1.900996,250,6.394622,5.705962,4,3.749408,7
579,LA,145,766,884-4897,no,no,0,8.351726,2,4.621966,6.781036,1,7.206054,3.767245,150,5.305655,4.220752,8,6.579940,4
4213,MO,55,777,582-3883,no,no,0,11.873993,5,7.830876,7.474179,2,7.955477,4.069518,100,6.469040,5.628250,7,6.066328,4

In [10]:
df.to_csv('./data/unlabeled.csv', header=None,index=False)